#!/bin/bash
# 多GPU部署脚本 - 每个GPU启动一个unified_api实例
# Multi-GPU Deployment Script - Launch unified_api instance per GPU

set -e

# 配置参数
DEFAULT_PORT=5002
WORKERS_PER_GPU=8
MAX_FILE_SIZE=500  # MB
MODEL="large-v3-turbo"
LOG_LEVEL="INFO"

# 颜色定义
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# 日志函数
log_info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

log_blue() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

# 检查CUDA是否可用
check_cuda() {
    if ! command -v nvidia-smi &> /dev/null; then
        log_error "nvidia-smi not found. Please install NVIDIA drivers."
        exit 1
    fi

    # 获取GPU数量
    GPU_COUNT=$(nvidia-smi --list-gpus | wc -l)
    log_info "Detected $GPU_COUNT GPU(s)"

    if [ $GPU_COUNT -eq 0 ]; then
        log_error "No GPUs detected. Please check your NVIDIA installation."
        exit 1
    fi
}

# 清理现有进程
cleanup() {
    log_info "Cleaning up existing unified_api processes..."

    # 查找并终止现有的unified_api进程
    PIDS=$(pgrep -f "unified_api.py" || true)
    if [ ! -z "$PIDS" ]; then
        log_warn "Found existing unified_api processes: $PIDS"
        kill $PIDS
        sleep 3

        # 强制终止仍在运行的进程
        REMAINING=$(pgrep -f "unified_api.py" || true)
        if [ ! -z "$REMAINING" ]; then
            log_warn "Force killing remaining processes: $REMAINING"
            kill -9 $REMAINING
        fi
    fi

    # 清理共享内存
    log_info "Cleaning up shared memory..."
    rm -f /dev/shm/whisper_* 2>/dev/null || true

    log_info "Cleanup completed"
}

# 检查端口是否被占用
check_port() {
    local port=$1
    if lsof -Pi :$port -sTCP:LISTEN -t >/dev/null 2>&1; then
        log_warn "Port $port is already in use"
        return 1
    fi
    return 0
}

# 启动单个GPU的unified_api实例
start_gpu_instance() {
    local gpu_id=$1
    local port=$2
    local workers=$3

    log_blue "Starting unified_api for GPU $gpu_id on port $port (workers: $workers)"

    # 检查端口
    if check_port $port; then
        log_error "Port $port is already in use. Skipping GPU $gpu_id."
        return 1
    fi

    # 创建日志目录
    LOG_DIR="logs/gpu_${gpu_id}"
    mkdir -p "$LOG_DIR"

    # 启动服务
    nohup python unified_api.py \
        --gpus "$gpu_id" \
        --port "$port" \
        --workers-per-gpu "$workers" \
        --model "$MODEL" \
        --log-level "$LOG_LEVEL" \
        --max-file-size "$MAX_FILE_SIZE" \
        > "$LOG_DIR/unified_api.log" 2>&1 &

    local pid=$!
    echo $pid

    # 等待服务启动
    sleep 5

    # 检查进程是否仍在运行
    if kill -0 $pid 2>/dev/null; then
        log_info "✅ GPU $gpu_id unified_api started successfully (PID: $pid, Port: $port)"

        # 健康检查
        for i in {1..10}; do
            if curl -s "http://localhost:$port/health" >/dev/null 2>&1; then
                log_info "✅ GPU $gpu_id health check passed"
                return 0
            fi
            sleep 2
        done

        log_warn "⚠️  GPU $gpu_id health check failed, but process is running"
        return 0
    else
        log_error "❌ GPU $gpu_id unified_api failed to start"
        return 1
    fi
}

# 显示部署状态
show_status() {
    log_info "=== Deployment Status ==="

    echo ""
    echo "Running unified_api instances:"
    ps aux | grep "python unified_api.py" | grep -v grep || echo "No instances running"

    echo ""
    echo "Port usage:"
    netstat -tlnp 2>/dev/null | grep ":$DEFAULT_PORT" || echo "No processes listening on default ports"

    echo ""
    echo "GPU usage:"
    nvidia-smi --query-gpu=index,name,memory.used,memory.total,utilization.gpu --format=csv,noheader,nounits | \
    while IFS=, read -r idx name mem_used mem_total gpu_util; do
        echo "GPU $idx ($name): ${mem_used}MB/${mem_total}MB (${gpu_util}% utilized)"
    done

    echo ""
    echo "Load balancer endpoints:"
    for ((i=0; i<GPU_COUNT; i++)); do
        local port=$((DEFAULT_PORT + i))
        echo "  http://localhost:$port/inference (GPU $i)"
    done
}

# 生成load_balancer配置
generate_lb_config() {
    local config_file="load_balancer_config.env"

    log_info "Generating load balancer configuration: $config_file"

    cat > "$config_file" << EOF
# Load Balancer Configuration for Multi-GPU unified_api
# Generated by deploy_multi_gpu.sh

# Backend services (one per GPU)
BACKEND_SERVICES=
EOF

    for ((i=0; i<GPU_COUNT; i++)); do
        local port=$((DEFAULT_PORT + i))
        echo "http://localhost:$port"
    done >> "$config_file"

    # 替换最后一行的换行符为逗号
    sed -i '$ s/$/, /' "$config_file"

    # 读取所有端口并格式化
    local ports=""
    for ((i=0; i<GPU_COUNT; i++)); do
        local port=$((DEFAULT_PORT + i))
        if [ $i -eq 0 ]; then
            ports="http://localhost:$port"
        else
            ports="$ports,http://localhost:$port"
        fi
    done

    # 更新配置文件
    sed -i "s/BACKEND_SERVICES=/BACKEND_SERVICES=$ports/" "$config_file"

    cat >> "$config_file" << EOF

# Load Balancer Configuration
LB_PORT=5001
MAX_QUEUE_SIZE=100
REQUEST_TIMEOUT=3600
HEALTH_CHECK_INTERVAL=30
MAX_FILE_SIZE=$MAX_FILE_SIZE

# Logging
LOG_LEVEL=INFO
EOF

    log_info "Configuration saved to: $config_file"
    log_info "Use: source $config_file && python load_balancer.py"
}

# 主函数
main() {
    log_info "=== Multi-GPU unified_api Deployment Script ==="
    log_info "Configuration: $WORKERS_PER_GPU workers per GPU, $MAX_FILE_SIZE MB max file size"

    # 检查CUDA
    check_cuda

    # 清理现有进程
    cleanup

    # 解析命令行参数
    WORKERS_PER_GPU=${1:-$WORKERS_PER_GPU}
    MAX_FILE_SIZE=${2:-$MAX_FILE_SIZE}
    MODEL=${3:-$MODEL}

    log_info "Deployment parameters:"
    log_info "  Workers per GPU: $WORKERS_PER_GPU"
    log_info "  Max file size: ${MAX_FILE_SIZE}MB"
    log_info "  Model: $MODEL"
    log_info "  Starting port: $DEFAULT_PORT"

    # 启动所有GPU实例
    log_info "Starting unified_api instances..."
    SUCCESS_COUNT=0

    for ((i=0; i<GPU_COUNT; i++)); do
        local port=$((DEFAULT_PORT + i))

        if start_gpu_instance $i $port $WORKERS_PER_GPU; then
            ((SUCCESS_COUNT++))
        fi

        # 错开启动时间避免资源竞争
        sleep 2
    done

    log_info "Deployment summary: $SUCCESS_COUNT/$GPU_COUNT instances started successfully"

    # 等待所有服务完全启动
    log_info "Waiting for services to fully initialize..."
    sleep 10

    # 显示状态
    show_status

    # 生成配置文件
    generate_lb_config

    log_info "=== Deployment Complete ==="
    log_info "Next steps:"
    log_info "1. Test individual instances: curl http://localhost:$DEFAULT_PORT/test-json"
    log_info "2. Start load balancer: source load_balancer_config.env && python load_balancer.py"
    log_info "3. Test load balancer: curl -X POST -F 'file=@test.wav' http://localhost:5001/inference"
    log_info "4. Monitor logs: tail -f logs/gpu_*/unified_api.log"

    log_info "To stop all instances: ./stop_multi_gpu.sh"
    log_info "To check status: ./show_status.sh"
}

# 创建停止脚本
create_stop_script() {
    cat > stop_multi_gpu.sh << 'EOF'
#!/bin/bash
# 停止所有unified_api实例

set -e

RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m'

log_info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

log_info "Stopping all unified_api processes..."

# 查找并终止进程
PIDS=$(pgrep -f "unified_api.py" || true)
if [ ! -z "$PIDS" ]; then
    log_info "Found processes: $PIDS"
    kill $PIDS
    sleep 3

    # 强制终止仍在运行的进程
    REMAINING=$(pgrep -f "unified_api.py" || true)
    if [ ! -z "$REMAINING" ]; then
        log_error "Force killing remaining processes: $REMAINING"
        kill -9 $REMAINING
    fi

    log_info "All processes stopped"
else
    log_info "No unified_api processes found"
fi

# 清理共享内存
log_info "Cleaning up shared memory..."
rm -f /dev/shm/whisper_* 2>/dev/null || true

log_info "Cleanup completed"
EOF

    chmod +x stop_multi_gpu.sh
}

# 创建状态检查脚本
create_status_script() {
    cat > show_status.sh << 'EOF'
#!/bin/bash
# 显示部署状态

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

log_info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

# 检查进程状态
echo "=== Unified API Process Status ==="
if pgrep -f "unified_api.py" >/dev/null; then
    log_info "Running unified_api processes:"
    ps aux | grep "python unified_api.py" | grep -v grep | \
    while read line; do
        echo "  $line"
    done
else
    echo "No unified_api processes running"
fi

echo ""

# 检查端口状态
echo "=== Port Status ==="
for port in 5002 5003 5004 5005; do
    if lsof -Pi :$port -sTCP:LISTEN -t >/dev/null 2>&1; then
        log_info "Port $port: In use"
        # 显示进程信息
        pid=$(lsof -Pi :$port -sTCP:LISTEN -t | awk 'NR==1 {print $2}')
        if [ ! -z "$pid" ]; then
            cmd=$(ps -p $pid -o cmd --no-headers 2>/dev/null || echo "Unknown")
            echo "  Process: $pid ($cmd)"
        fi
    else
        echo "Port $port: Available"
    fi
done

echo ""

# 检查GPU状态
echo "=== GPU Status ==="
if command -v nvidia-smi &> /dev/null; then
    nvidia-smi --query-gpu=index,name,memory.used,memory.total,utilization.gpu,temperature.gpu --format=csv,noheader,nounits | \
    while IFS=, read -r idx name mem_used mem_total gpu_util temp; do
        if [ "$temp" = "-" ]; then
            temp="N/A"
        fi
        echo "GPU $idx ($name): ${mem_used}MB/${mem_total}MB (${gpu_util}% GPU, ${temp}°C)"
    done
else
    echo "nvidia-smi not available"
fi

echo ""

# 检查API健康状态
echo "=== API Health Status ==="
for port in 5002 5003 5004 5005; do
    if curl -s "http://localhost:$port/health" >/dev/null 2>&1; then
        log_info "Port $port: Healthy"
    elif lsof -Pi :$port -sTCP:LISTEN -t >/dev/null 2>&1; then
        echo "Port $port: Running but unhealthy"
    else
        echo "Port $port: Not responding"
    fi
done
EOF

    chmod +x show_status.sh
}

# 创建脚本
create_stop_script
create_status_script

# 如果直接运行此脚本，执行主函数
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    main "$@"
fi